title: "BuildingBloCS"
tagline: "High School Computing Conference"
date: "Date TBC"
location: "Location TBC"
instagram: "buildingblocs21"
github: "buildingblocs"

exclude:
  - README.md
  - assets/sass
  - package.json
  - node_modules/
  - Gruntfile.js
  - .jekyll-cache/
  - .template/
